grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 3



model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      n_estimators: [100, 130]
      criterion: ['gini', 'entropy']
      max_depth: [8, 9]  # Since range() isn't directly usable, adjusted to a list
      n_jobs: -1
    search_param_grid:
      n_estimators: [100, 130]
      criterion: ['gini', 'entropy']
      max_depth: [8, 9]  # Adjusted the range as a list [8, 9]
      n_jobs: [-1]

